global: # Metric 정보 수집 주기

scrape_configs:
  - job_name: "ec2 server"
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets:
          - "13.209.204.40:9100"

  - job_name: "RDS Exporter Basic"
    scrape_interval: 60s
    scrape_timeout: 55s
    metrics_path: /basic  # 이 경로가 실제로 유효한지 확인 필요
    honor_labels: true
    honor_timestamps: false
    static_configs:
      - targets:
          - "13.209.204.40:9042"
